spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/MedicalRecord_prod
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8083
