spring:
  application:
    name: MedicalRecordsManagement

  profiles:
    active: test

jwt:
  expriMinutes: 3600
  expireDate: 5
  accesskey: 2mfGKBhdCa0K8X2uV1Fzn9o6sR8V0s5GUelGlxsFQAc=
  refreshkey: /AqIfLpfbWqy36D3VBmkskYtmnpsJrLpRx00WVRnJlE=

openapi:
  service:
    api-docs: api-service

#  xkdi lnwb rtoy meyu

